# Generated by Django 2.0.6 on 2018-06-25 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.TextField(max_length=100)),
                ('location_name', models.TextField(max_length=100)),
            ],
        ),
    ]
