# Generated by Django 2.0.6 on 2018-06-25 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Check_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.BooleanField(default=False)),
                ('smell', models.BooleanField(default=False)),
                ('wall', models.BooleanField(default=False)),
                ('dustbin', models.BooleanField(default=False)),
                ('toilet_bowl', models.BooleanField(default=False)),
                ('urinal_bowl', models.BooleanField(default=False)),
                ('wash_basin', models.BooleanField(default=False)),
                ('mirror', models.BooleanField(default=False)),
                ('tissue', models.BooleanField(default=False)),
                ('handsoap', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('location_id', models.TextField(max_length=100)),
                ('employee_number', models.TextField(max_length=100)),
                ('supervisor_type', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor', models.IntegerField()),
                ('supervisor_type', models.TextField(max_length=100)),
                ('name', models.TextField(max_length=100)),
                ('authorization_token', models.TextField(default=None, max_length=100)),
                ('authorization_expire', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='check_item',
            name='checklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supervisor.Checklist'),
        ),
    ]
