# Generated by Django 2.0.6 on 2018-06-25 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisor',
            name='authorization_token',
            field=models.TextField(blank=True, default=None, max_length=100),
        ),
    ]
